### ISSUE TITLE
Seasons not found when running script

### ISSUE THREAD

**Issue by rtgurley** [RiyeUK/plex-mediUX-title-cards#2]
I have added a series to my TV_Shows.yml file.  When I run the command I get this response:
```

> `root@Gurley:/mnt/user/appdata/MediaUX/plex-mediUX-title-cards# python3 plex-title-cards.py TV_Shows.yml 
> Adding to Library 'TV Shows'
> Poster uploaded successfully for 'The Big Door Prize'
> Background uploaded successfully for 'The Big Door Prize'
> Season 1 not found for 'The Big Door Prize'
> Season 2 not found for 'The Big Door Prize'`

```

Do my Seasons folders or file names need to be named in a certain format?  I currently have it as The Big Door Prize/Season 1/The Big Door Prize - S01E01.mkv
What else may cause this.
[TV_Shows.yml.zip](https://github.com/RiyeUK/plex-mediUX-title-cards/files/15183629/TV_Shows.yml.zip)

**Comment by RiyeUK** [comment]
Hi @rtgurley, sorry about the delay. It looks like you're passing in strings instead of numbers for the ids:

```yaml
    seasons:
      '1':
        url_poster: 'https://api.mediux.pro/assets/72646e92-04eb-4047-b835-8f08b983ba25'
        episodes:
          '1':
```
instead of
```yaml
    seasons:
      1:
        url_poster: 'https://api.mediux.pro/assets/72646e92-04eb-4047-b835-8f08b983ba25'
        episodes:
          1:
```
So the system is looking for a season called '1' instead of Season 1 (the first season).
I'll put in a quick fix for this.
